import React, { useEffect } from 'react'
import CreateEventOneOnOne from '../../../../components/createEvent/CreateEventOneOnOne'
import AppNavbar from '../../../../components/AppNavbar'
import Head from 'next/head'
import { getCookie } from "cookies-next"
import jwt from "jsonwebtoken";
import useStateContext from '../../../../context/ContextProvider'
import { useRouter } from 'next/router';


const oneOnOne = ({ user }) => {
    const { setCookieUser, setAllSchedule } = useStateContext();
    useEffect(() => {
        // setting logged-in user from cookie in contextAPI 
        setCookieUser(user);
        // setting users availability
        setAllSchedule(user.availability);
    }, []);
    const { eventType } = useRouter().query;
    return (
        <div className='w-screen h-screen' >
            <Head>
                <title>Turpio | Creating Event</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <AppNavbar
                pageTitle="One-on-One"
                disableSecondControl={true}
                backBtn={true}
            />
            <CreateEventOneOnOne
                user={user}
                eventType={eventType}
                nextLink="one-on-one/availability"
            />
        </div>
    )
}

export default oneOnOne

export const getServerSideProps = async function ({ req, res }) {
    const userToken = getCookie("userAccountToken", { req, res });
    if (!userToken) {
        return {
            redirect: {
                destination: '/login?redirect_url=' + req.url,
                permanent: true,
            },
        }
    } else {
        const user = jwt.verify(userToken, process.env.JWT_KEY)
        return {
            props: { user },
        }
    }
}